{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rabbitmq-operator.serviceAccountName" . }}
  labels:
{{ include "rabbitmq-operator.labels" . | indent 4 }}
{{- end -}}
